#!/bin/bash

# Move XSD schema files before generating stubs.
# We do this because validating against the schema files produces an error.
mv specs/xsd-ref/*.xsd specs/

# Delete previously generated stubs.
rm -rf stubs && mkdir -p stubs

# Change the "Platform" area name in area105-v002-Platform.xml to "PL".
# This is to avoid a conflict with code generated by zproject/gsl in the CCSDS MO MAL C SEPP Apps project.
cp specs/xml/area105-v002-Platform.xml specs/xml/area105-v002-Platform.xml.backup
sed -i 's/name="Platform"/name="PF"/g' specs/xml/area105-v002-Platform.xml
sed -i 's/area=\"Platform\"/area="PF"/g' specs/xml/area105-v002-Platform.xml

# Generate stubs.
java -jar PLUGIN/target/StubGenerator-jar-with-dependencies.jar -t C -x specs/xml -r specs/xml-ref -R specs/xsd-ref -o stubs -f

# Restore the original version of the "Platform" XML specs files with the area name as "Platform" instead of "PF".
mv specs/xml/area105-v002-Platform.xml.backup specs/xml/area105-v002-Platform.xml

# Move XSD schema files back to their folder.
mv specs/*.xsd specs/xsd-ref/
